"""Initial database schema

Revision ID: 787e7694aa32
Revises: 
Create Date: 2026-05-25 20:04:51.886012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '787e7694aa32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_settings_key'), ['key'], unique=True)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asin', sa.String(length=32), nullable=False),
    sa.Column('jan', sa.String(length=32), nullable=True),
    sa.Column('ean', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('category_id', sa.String(length=64), nullable=True),
    sa.Column('category_name', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('amazon_url', sa.Text(), nullable=True),
    sa.Column('keepa_url', sa.Text(), nullable=True),
    sa.Column('current_price', sa.Integer(), nullable=True),
    sa.Column('avg_price_30', sa.Integer(), nullable=True),
    sa.Column('avg_price_90', sa.Integer(), nullable=True),
    sa.Column('lowest_price_90', sa.Integer(), nullable=True),
    sa.Column('highest_price_90', sa.Integer(), nullable=True),
    sa.Column('sales_rank_current', sa.Integer(), nullable=True),
    sa.Column('sales_rank_avg_30', sa.Integer(), nullable=True),
    sa.Column('sales_rank_avg_90', sa.Integer(), nullable=True),
    sa.Column('sales_rank_drops_30', sa.Integer(), nullable=True),
    sa.Column('sales_rank_drops_90', sa.Integer(), nullable=True),
    sa.Column('new_offer_count', sa.Integer(), nullable=True),
    sa.Column('used_offer_count', sa.Integer(), nullable=True),
    sa.Column('fba_offer_count', sa.Integer(), nullable=True),
    sa.Column('amazon_in_stock', sa.Boolean(), nullable=True),
    sa.Column('amazon_was_in_stock_90', sa.Boolean(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('price_stability_score', sa.Integer(), nullable=True),
    sa.Column('sales_score', sa.Integer(), nullable=True),
    sa.Column('competition_score', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('keepa_score', sa.Integer(), nullable=True),
    sa.Column('judgement', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('raw_keepa_json', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_asin'), ['asin'], unique=True)

    op.create_table('research_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('keyword', sa.String(length=255), nullable=True),
    sa.Column('category_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('conditions_json', sa.Text(), nullable=True),
    sa.Column('total_requested', sa.Integer(), nullable=False),
    sa.Column('total_fetched', sa.Integer(), nullable=False),
    sa.Column('total_saved', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_research_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('research_run_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_research_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_research_runs_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_research_runs_research_run_id'), ['research_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_research_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_research_runs_research_run_id'))
        batch_op.drop_index(batch_op.f('ix_product_research_runs_product_id'))

    op.drop_table('product_research_runs')
    op.drop_table('research_runs')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_asin'))

    op.drop_table('products')
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_settings_key'))

    op.drop_table('app_settings')
    # ### end Alembic commands ###
